# on: push
# name: Deploy with commit message
# jobs:
#   web-deploy:
#     name: Deploy
#     runs-on: ubuntu-latest
#     steps:
#     - name: Get latest code
#       uses: actions/checkout@v3

#     - name: Check commit message
#       id: check-message
#       run: |
#         commit_message=$(git log --format=%B -n 1 ${{ github.event.after }})
#         echo "Commit message: $commit_message"
#         if [[ "$commit_message" =~ \[deploy\] ]]; then
#           echo "should_deploy=true" >> $GITHUB_ENV
#         else
#           echo "should_deploy=false" >> $GITHUB_ENV
#         fi
        

#     # - name:  Sync files
#     #   if: env.should_deploy == 'true'
#     #   uses: SamKirkland/FTP-Deploy-Action@v4.3.4
#     #   with:
#     #     server: s36.cyber-folks.pl 
#     #     username: dev@dsmkt-dev.mcpl6a.cfolks.pl
#     #     password: rCH-#fg-U_Z791me
#     #     protocol: ftps
#     #     local-dir: ./dsmkt2024/
#     #     server-dir: public_html/

#     # - name: Custom FTP Deploy
#     #   if: env.should_deploy == 'true'
#     #   run: |
#     #     lftp -c "
#     #     set ftps:initial-prot '';
#     #     set ftp:ssl-force true;
#     #     open -u dev@dsmkt-dev.mcpl6a.cfolks.pl, rCH-#fg-U_Z791me s36.cyber-folks.pl ;
#     #     lcd ./dsmkt2024/;
#     #     cd public_html/;
#     #     mirror --reverse --delete --verbose ./dsmkt2024/ public_html/;
#     #     "

#     - name: Install lftp
#       if: env.should_deploy == 'true'
#       run: sudo apt-get update && sudo apt-get install -y lftp

#     - name: Sync files with lftp
#       if: env.should_deploy == 'true'
#       run: |
#         lftp -c "
#         set ftps:initial-prot '';
#         set ftp:ssl-force true;
#         set ssl:verify-certificate no;
#         open -u dev@dsmkt-dev.mcpl6a.cfolks.pl,rCH-#fg-U_Z791me s36.cyber-folks.pl;
#         ls;
#         lcd dsmkt2024;
#         cd public_html/;
#         mirror --reverse --delete --verbose ./dsmkt2024/ public_html/;
#         "
#       env:
#         FTP_USERNAME: dev@dsmkt-dev.mcpl6a.cfolks.pl
#         FTP_PASSWORD: rCH-#fg-U_Z791me
#         FTP_SERVER: s36.cyber-folks.pl